services:
  - type: web
    name: avtosotuv
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    healthCheckPath: /api/test/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,avtosotuv.uz"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com,https://avtosotuv.uz"
      - key: DATABASE_URL
        fromDatabase:
          name: avtosotuv-db
          property: connectionString

databases:
  - name: avtosotuv-db
    plan: free
